### ISSUE TITLE
no matching client->server cipher

### ISSUE THREAD

**Issue by sholiverlee** [realtymaps/promise-sftp#15]
When connect to a sftp server, get an error:

Error: Handshake failed: no matching client->server cipher
    at check_KEXINIT (/Users/WebstormProjects/backend/node_modules/ssh2-streams/lib/ssh.js:2343:15)
    at check (/Users/WebstormProjects/backend/node_modules/ssh2-streams/lib/ssh.js:2222:9)
    at onKEXINIT (/Users/WebstormProjects/backend/node_modules/ssh2-streams/lib/ssh.js:2219:5)
    at SSH2Stream.<anonymous> (/Users/WebstormProjects/backend/node_modules/ssh2-streams/lib/ssh.js:206:5)
    at emitTwo (events.js:126:13)
    at SSH2Stream.emit (events.js:214:7)
    at parse_KEXINIT (/Users/WebstormProjects/backend/node_modules/ssh2-streams/lib/ssh.js:4117:8)
    at parsePacket (/Users/WebstormProjects/backend/node_modules/ssh2-streams/lib/ssh.js:4013:12)
    at SSH2Stream._transform (/Users/WebstormProjects/backend/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/Users/WebstormProjects/backend/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)

**Comment by sholiverlee** [comment]
Solved. After debug, add server cipher. 

 algorithms: {
      cipher: ['aes128-cbc', 'aes192-cbc', 'aes256-cbc', '3des-cbc', 'blowfish-cbc']
    }

**Comment by redbonzai** [comment]
Is this an option added to the connect() method ? 
like this ? 
```class Ftp {
    constructor() {
        this.config = {
            host: process.env.FTPHOST, 
            port:22,
            user: process.env.FTPUSER, 
            password: process.env.FTPPASS,
            algorithms: {
                cipher: ['aes128-cbc', 'aes192-cbc', 'aes256-cbc', '3des-cbc', 'blowfish-cbc']
            }            
        }
        this.ftp = new PromiseSftp();
        this.fs = promisify('fs')
    }

    ftpConnect() {
        this.ftp.connect(this.config)
        .then(result => console.log('FTP Connection result: ', result))
        .catch((err) => {
            console.log('connection error: ', err)
        })
    }```
Because I am having this problem, and I don't see in the documentation how to remedy this.

**Comment by redbonzai** [comment]
> Solved. After debug, add server cipher.
> 
> algorithms: {
> cipher: ['aes128-cbc', 'aes192-cbc', 'aes256-cbc', '3des-cbc', 'blowfish-cbc']
> }
How do you implement this solution?
