### ISSUE TITLE
Put resolves promise before the actual file transfer is completed

### ISSUE THREAD

**Issue by ozankaya** [realtymaps/promise-sftp#7]
We are experiencing this issue intermittently during uploading multiple files via SFTP. All the promises with **put** method are resolving successfully but we receive the exception below when **end** method is called.

> events.js:160
      throw er; // Unhandled 'error' event
      ^

> Error: The requested operation cannot be performed because there is a file transfer in progress.
    at SFTPStream._transform (/var/app/current/node_modules/ssh2-streams/lib/sftp.js:410:27)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/var/app/current/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at SFTPStream.Writable.write (_stream_writable.js:247:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at SSH2Stream.<anonymous> (/var/app/current/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/var/app/current/node_modules/ssh2-streams/lib/ssh.js:3443:10)
    at SSH2Stream._transform (/var/app/current/node_modules/ssh2-streams/lib/ssh.js:668:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/var/app/current/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at SSH2Stream.Writable.write (_stream_writable.js:247:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by jonymusky** [comment]
Hi, I am experimenting the same issue.
